let buttonStart = document.getElementById("start");
let divValueClass = document.querySelectorAll("div[class*='value']");
let inputExpense = document.querySelectorAll(".expenses-item");
let buttonTag = document.querySelectorAll("button:not(.start)");
let inputOptionalExpense = document.querySelectorAll(".optionalexpenses-item");
let inputProbableExpense = document.querySelector("#income");
let checkSavings = document.querySelector("#savings");
let inputSum = document.querySelector("#sum");
let inputPercent = document.querySelector("#percent");
let inputYMD = document.querySelectorAll(".time-data input");